=== xalpha/Calibrated-Photometric-Stereo/data/config/configurationCPS.xsd
<?xml version="1.0"?>

<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
>

<!--                    -->
<!-- Definition of type -->
<!--                    -->

<!-- string -->
<xs:simpleType name="BooleanType">
	<xs:restriction base="xs:boolean" />
</xs:simpleType>
<xs:simpleType name="StringType">
	<xs:restriction base="xs:string" />
</xs:simpleType>
<!-- decimal values: 0.1, -3.5, ...-->
<xs:simpleType name="DecimalType">
	<xs:restriction base="xs:decimal" />
</xs:simpleType>
<!-- integer value: -4, 0, 20 -->
<xs:simpleType name="IntType">
	<xs:restriction base="xs:integer" />
</xs:simpleType>
<!-- positive integer value: 1, 2, ... -->
<xs:simpleType name="IntPosType">
	<xs:restriction base="xs:positiveInteger" />
</xs:simpleType>
<!-- non-positive integer value: ..., -2, -1, 0 -->
<xs:simpleType name="IntNonPosType">
	<xs:restriction base="xs:nonPositiveInteger" />
</xs:simpleType>
<!-- positive integer value: ..., -2, -1 -->
<xs:simpleType name="IntNegType">
	<xs:restriction base="xs:negativeInteger" />
</xs:simpleType>
<!-- non-positive integer value: 0, 1, 2, ... -->
<xs:simpleType name="IntNonNegType">
	<xs:restriction base="xs:nonNegativeInteger" />
</xs:simpleType>
<!-- list of xs:string -->
<xs:simpleType name="StringList">
	<xs:list itemType="StringType" />
</xs:simpleType>
<!-- list of xs:decimal -->
<xs:simpleType name="DecimalList">
	<xs:list itemType="DecimalType" />
</xs:simpleType>
<!-- list of xs:nonNegativeInteger -->
<xs:simpleType name="IntNonNegList">
	<xs:list itemType="IntNonNegType" />
</xs:simpleType>

<!--                                 -->
<!-- Definition of Reflectance model -->
<!--                                 -->
<xs:simpleType name="ReflectanceModelType">
	<xs:restriction base="StringType">
		<xs:enumeration value="Lambertian" />
		<xs:enumeration value="Phong" />
		<xs:enumeration value="Blinn-Phong" />
		<xs:enumeration value="Oren–Nayar" />
		<xs:enumeration value="Torrance-Sparrow" />
		<xs:enumeration value="Cook–Torrance" />
	</xs:restriction>
</xs:simpleType>

<!--                            -->
<!-- Definition of Light source -->
<!--                            -->
<xs:simpleType name="LightDirectionType">
	<xs:restriction base="StringType" />
</xs:simpleType>

<xs:simpleType name="LightIntensityType">
	<xs:restriction base="DecimalType" />
</xs:simpleType>

<!--                           -->
<!-- Definition of Observation -->
<!--                           -->
<xs:complexType name="ObservationSingleType">
	<xs:sequence>
		<xs:element name="Image" type="StringType" />
		<xs:element name="LightDirection" type="LightDirectionType" />
		<xs:element name="LightIntensity" type="LightIntensityType" />
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="ColorType">
	<xs:restriction base="IntNonNegType">
		<xs:enumeration value="1" />
		<xs:enumeration value="3" />
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="ObservationType">
	<xs:sequence>
		<xs:element name="DirectoryObservation" type="StringType" />
		<xs:element name="ObservationMask" minOccurs="0" type="StringType" />
		<xs:element name="ObservationSingle" minOccurs="3" maxOccurs="unbounded" type="ObservationSingleType" />
		<xs:element name="Color" type="ColorType" />
	</xs:sequence>
</xs:complexType>

<!--                                            -->
<!-- Definition of Calibrated Photometric Stereo-->
<!--                                            -->
<xs:complexType name="CalibratedPhotometricStereoType">
	<xs:sequence>
		<xs:element name="Observation" type="ObservationType" />
		<xs:element name="ReflectanceModel" type="ReflectanceModelType" />
		<xs:element name="DirectoryOutput" type="StringType" />
	</xs:sequence>
</xs:complexType>

<xs:element name="CalibratedPhotometricStereo" type="CalibratedPhotometricStereoType" />

</xs:schema>

=== xalpha/Calibrated-Photometric-Stereo/data/config/chrome.xml
<?xml version="1.0" encoding="UTF-8"?>

<CalibratedPhotometricStereo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configurationCPS.xsd">
	<Observation>
		<DirectoryObservation>../data/psmImages/chrome/</DirectoryObservation>
		<ObservationMask>chrome.mask.tga</ObservationMask>
		<ObservationSingle>
			<Image>chrome.0.tga</Image>
			<LightDirection>0.403259 0.480808 0.778592</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.1.tga</Image>
			<LightDirection>0.0982272 0.163712 0.981606</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.2.tga</Image>
			<LightDirection>-0.0654826 0.180077 0.98147</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.3.tga</Image>
			<LightDirection>-0.127999 0.431998 0.892745</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.4.tga</Image>
			<LightDirection>-0.328606 0.485085 0.810377</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.5.tga</Image>
			<LightDirection>-0.110339 0.53593 0.837021</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.6.tga</Image>
			<LightDirection>0.239071 0.41439 0.878138</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.7.tga</Image>
			<LightDirection>0.0642302 0.417497 0.906406</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.8.tga</Image>
			<LightDirection>0.12931 0.339438 0.931698</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.9.tga</Image>
			<LightDirection>0.0323953 0.340151 0.939813</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.10.tga</Image>
			<LightDirection>0.0985318 0.0492659 0.993914</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>chrome.11.tga</Image>
			<LightDirection>-0.16119 0.354617 0.921013</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<Color>3</Color>
	</Observation>
	<ReflectanceModel>Lambertian</ReflectanceModel>
	<DirectoryOutput>../data/result/chrome/</DirectoryOutput>
</CalibratedPhotometricStereo>

=== xalpha/Calibrated-Photometric-Stereo/data/config/cat.xml
<?xml version="1.0" encoding="UTF-8"?>

<CalibratedPhotometricStereo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configurationCPS.xsd">
	<Observation>
		<DirectoryObservation>../data/psmImages/cat/</DirectoryObservation>
		<ObservationMask>cat.mask.tga</ObservationMask>
		<ObservationSingle>
			<Image>cat.0.tga</Image>
			<LightDirection>0.403259 0.480808 0.778592</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.1.tga</Image>
			<LightDirection>0.0982272 0.163712 0.981606</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.2.tga</Image>
			<LightDirection>-0.0654826 0.180077 0.98147</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.3.tga</Image>
			<LightDirection>-0.127999 0.431998 0.892745</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.4.tga</Image>
			<LightDirection>-0.328606 0.485085 0.810377</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.5.tga</Image>
			<LightDirection>-0.110339 0.53593 0.837021</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.6.tga</Image>
			<LightDirection>0.239071 0.41439 0.878138</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.7.tga</Image>
			<LightDirection>0.0642302 0.417497 0.906406</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.8.tga</Image>
			<LightDirection>0.12931 0.339438 0.931698</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.9.tga</Image>
			<LightDirection>0.0323953 0.340151 0.939813</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.10.tga</Image>
			<LightDirection>0.0985318 0.0492659 0.993914</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<ObservationSingle>
			<Image>cat.11.tga</Image>
			<LightDirection>-0.16119 0.354617 0.921013</LightDirection>
			<LightIntensity>1.0</LightIntensity>
		</ObservationSingle>
		<Color>3</Color>
	</Observation>
	<ReflectanceModel>Lambertian</ReflectanceModel>
	<DirectoryOutput>../data/result/cat/</DirectoryOutput>
</CalibratedPhotometricStereo>
